version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "hello-genai-in-go/"
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "hello-genai-in-go/"
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns:
          - "*"